### ISSUE TITLE
Cryptocurrency tracker

### ISSUE THREAD

**Issue by Nitish-JS** [AP-Back/Web-Dev-Projects#17]
I want to work on a cryptocurrency tracker website using ReactJS

**Comment by AP-Back** [comment]
Yeah Sure!

**Comment by Nitish-JS** [comment]
Added cryptocurrency tracker website using reactjs and mui

@AP-Back  kindly merge the pull request #18  under the Hacktoberfest tag

**Comment by AP-Back** [comment]
> Added cryptocurrency tracker website using reactjs and mui
> 
> @AP-Back kindly merge the pull request #18 under the Hacktoberfest tag

Yeah Cool!

**Comment by AP-Back** [comment]
![image](https://user-images.githubusercontent.com/84858466/197485834-bc6ee723-d6e1-452c-9eb2-3d9ae5ea4630.png)
The project has some errors kindly fix and update

**Comment by Nitish-JS** [comment]
`
![noerror](https://user-images.githubusercontent.com/73771450/197492839-3a4a48c0-60f5-4262-a97d-c200d217c4cc.jpg)
`
The website is running fine for me and also it is deployed at https://cryptohunter-nitish.netlify.app/

**Comment by Nitish-JS** [comment]
![image](https://user-images.githubusercontent.com/73771450/197493453-14c4458a-1bda-488a-969a-86954993366a.png)

The code is working fine for me, also it is deployed at https://cryptohunter-nitish.netlify.app/
